Update zn-m2-n.yml

diff --git a/.github/workflows/zn-m2-n.yml b/.github/workflows/zn-m2-n.yml
--- a/.github/workflows/zn-m2-n.yml
+++ b/.github/workflows/zn-m2-n.yml
@@ -119,16 +119,38 @@ jobs:
         find dl -size -1024c -exec ls -l {} \;
         find dl -size -1024c -exec rm -f {} \;
 
+    # - name: Compile the firmware
+      # id: compile
+      # run: |
+        # cd openwrt
+        # echo -e "$(nproc) thread compile"
+        # make -j$(nproc) || make -j1 || make -j1 V=s
+        # echo "status=success" >> $GITHUB_OUTPUT
+        # grep '^CONFIG_TARGET.*DEVICE.*=y' .config | sed -r 's/.*DEVICE_(.*)=y/\1/' > DEVICE_NAME
+        # [ -s DEVICE_NAME ] && echo "DEVICE_NAME=_$(cat DEVICE_NAME)" >> $GITHUB_ENV
+        # echo "FILE_DATE=_$(date +"%Y%m%d%H%M")" >> $GITHUB_ENV
+
     - name: Compile the firmware
       id: compile
       run: |
         cd openwrt
         echo -e "$(nproc) thread compile"
-        make -j$(nproc) || make -j1 || make -j1 V=s
+        make -j$(nproc) V=s 2>&1 | tee build.log || make -j1 V=s 2>&1 | tee build.log || make -j1 V=sc 2>&1 | tee build.log
+        if [ ${PIPESTATUS[0]} -eq 0 ]; then
         echo "status=success" >> $GITHUB_OUTPUT
+        else
+        echo "status=failure" >> $GITHUB_OUTPUT
+        fi
         grep '^CONFIG_TARGET.*DEVICE.*=y' .config | sed -r 's/.*DEVICE_(.*)=y/\1/' > DEVICE_NAME
         [ -s DEVICE_NAME ] && echo "DEVICE_NAME=_$(cat DEVICE_NAME)" >> $GITHUB_ENV
         echo "FILE_DATE=_$(date +"%Y%m%d%H%M")" >> $GITHUB_ENV
+
+    - name: Upload build log
+      uses: actions/upload-artifact@v3
+      with:
+        name: openwrt-build-log
+        path: openwrt/build.log
+
 
     - name: Check space usage
       run: df -hT
